/**
 * ACP Event Ledger - Oracle
 */

import oracledb from "oracledb";

async function ensureTables(pool: oracledb.Pool) {
  const conn = await pool.getConnection();
  try {
    await conn.execute(`
      BEGIN
        EXECUTE IMMEDIATE '
          CREATE TABLE acp_events (
            id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            session_id VARCHAR2(64) NOT NULL,
            session_key VARCHAR2(255) NOT NULL,
            run_id VARCHAR2(64),
            event_type VARCHAR2(50) NOT NULL,
            event_data CLOB NOT NULL,
            created_at TIMESTAMP DEFAULT SYSTIMESTAMP
          )
        ';
      EXCEPTION
        WHEN OTHERS THEN
          IF SQLCODE != -955 THEN RAISE; END IF;
      END;
    `);
    await conn.commit();
  } finally {
    await conn.close();
  }
}

export async function saveEvent(params: {
  pool: oracledb.Pool;
  sessionId: string;
  sessionKey: string;
  runId?: string;
  eventType: string;
  data: any;
}) {
  await ensureTables(params.pool);
  const conn = await params.pool.getConnection();
  try {
    await conn.execute(
      `INSERT INTO acp_events (session_id, session_key, run_id, event_type, event_data)
       VALUES (:sessionId, :sessionKey, :runId, :eventType, :eventData)`,
      {
        sessionId: params.sessionId,
        sessionKey: params.sessionKey,
        runId: params.runId || null,
        eventType: params.eventType,
        eventData: JSON.stringify(params.data),
      }
    );
    await conn.commit();
  } finally {
    await conn.close();
  }
}

export async function getEvents(params: {
  pool: oracledb.Pool;
  sessionId: string;
  limit?: number;
}) {
  await ensureTables(params.pool);
  const conn = await params.pool.getConnection();
  try {
    const result = await conn.execute(
      `SELECT event_type, event_data, created_at
       FROM acp_events
       WHERE session_id = :sessionId
       ORDER BY created_at ASC
       FETCH FIRST :limit ROWS ONLY`,
      {
        sessionId: params.sessionId,
        limit: params.limit || 1000,
      }
    );
    return (result.rows || []).map((row: any) => ({
      type: row[0],
      data: JSON.parse(row[1]),
      createdAt: row[2],
    }));
  } finally {
    await conn.close();
  }
}