import oracledb from "oracledb";

async function getConnection(): Promise<oracledb.Connection> {
  return oracledb.getConnection({
    user: process.env.ORACLE_USER,
    password: process.env.ORACLE_PASSWORD,
    connectString: process.env.ORACLE_DSN,
  });
}

async function ensureTable(): Promise<void> {
  const conn = await getConnection();
  await conn.execute(`
    BEGIN
      EXECUTE IMMEDIATE '
        CREATE TABLE matrix_idb_snapshot (
          id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          name VARCHAR2(255) NOT NULL,
          version NUMBER NOT NULL,
          stores CLOB NOT NULL,
          created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
      ';
    EXCEPTION
      WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
    END;
  `);
  await conn.close();
}

export async function persistIdbToOracle(params: {
  name: string;
  version: number;
  stores: string;
}): Promise<void> {
  await ensureTable();
  const conn = await getConnection();
  await conn.execute(
    `INSERT INTO matrix_idb_snapshot (name, version, stores) VALUES (:name, :version, :stores)`,
    params,
  );
  await conn.close();
}

export async function restoreIdbFromOracle(): Promise<{
  name: string;
  version: number;
  stores: string;
} | null> {
  await ensureTable();
  const conn = await getConnection();
  const result = await conn.execute(
    `SELECT name, version, stores FROM matrix_idb_snapshot ORDER BY created_at DESC FETCH FIRST 1 ROW ONLY`,
  );
  await conn.close();
  if (result.rows.length === 0) return null;
  const row = result.rows[0];
  return { name: row[0], version: row[1], stores: row[2] };
}