import oracledb from "oracledb";
import { decodeRecoveryKey } from "matrix-js-sdk/lib/crypto-api/recovery-key.js";
import { formatMatrixErrorMessage, formatMatrixErrorReason } from "../errors.js";
import { LogService } from "./logger.js";
import type {
  MatrixCryptoBootstrapApi,
  MatrixCryptoCallbacks,
  MatrixGeneratedSecretStorageKey,
  MatrixSecretStorageStatus,
  MatrixStoredRecoveryKey,
} from "./types.js";

async function getConnection(): Promise<oracledb.Connection> {
  return oracledb.getConnection({
    user: process.env.ORACLE_USER,
    password: process.env.ORACLE_PASSWORD,
    connectString: process.env.ORACLE_DSN,
  });
}

async function ensureTable(): Promise<void> {
  const conn = await getConnection();
  await conn.execute(`
    BEGIN
      EXECUTE IMMEDIATE '
        CREATE TABLE matrix_recovery_key (
          id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          version NUMBER NOT NULL,
          key_id VARCHAR2(255),
          encoded_private_key CLOB NOT NULL,
          private_key_base64 CLOB NOT NULL,
          key_info_passphrase VARCHAR2(1000),
          key_info_name VARCHAR2(255),
          created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
      ';
    EXCEPTION
      WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
    END;
  `);
  await conn.close();
}

async function loadStoredRecoveryKey(): Promise<MatrixStoredRecoveryKey | null> {
  await ensureTable();
  const conn = await getConnection();
  const result = await conn.execute(
    `SELECT version, key_id, encoded_private_key, private_key_base64, key_info_passphrase, key_info_name, created_at
     FROM matrix_recovery_key
     ORDER BY created_at DESC
     FETCH FIRST 1 ROW ONLY`
  );
  await conn.close();
  if (result.rows.length === 0) return null;
  const row = result.rows[0];
  return {
    version: row[0],
    keyId: row[1],
    encodedPrivateKey: row[2],
    privateKeyBase64: row[3],
    keyInfo: row[4] || row[5] ? { passphrase: row[4], name: row[5] } : undefined,
    createdAt: row[6],
  };
}

async function saveRecoveryKeyToDisk(params: MatrixGeneratedSecretStorageKey): Promise<void> {
  await ensureTable();
  const conn = await getConnection();
  await conn.execute(
    `INSERT INTO matrix_recovery_key (version, key_id, encoded_private_key, private_key_base64, key_info_passphrase, key_info_name)
     VALUES (:version, :keyId, :encodedPrivateKey, :privateKeyBase64, :passphrase, :name)`,
    {
      version: 1,
      keyId: params.keyId ?? null,
      encodedPrivateKey: params.encodedPrivateKey,
      privateKeyBase64: Buffer.from(params.privateKey).toString("base64"),
      passphrase: params.keyInfo?.passphrase ?? null,
      name: params.keyInfo?.name ?? null,
    }
  );
  await conn.close();
}

export function isRepairableSecretStorageAccessError(err: unknown): boolean {
  const message = formatMatrixErrorReason(err);
  if (!message) return false;
  if (message.includes("getsecretstoragekey callback returned falsey")) return true;
  if (message.includes("decrypting secret") && message.includes("bad mac")) return true;
  return false;
}

export class MatrixRecoveryKeyStore {
  private readonly secretStorageKeyCache = new Map<
    string,
    { key: Uint8Array; keyInfo?: MatrixStoredRecoveryKey["keyInfo"] }
  >();
  private stagedRecoveryKey: MatrixStoredRecoveryKey | null = null;
  private stagedRecoveryKeyUsed = false;
  private readonly stagedCacheKeyIds = new Set<string>();

  buildCryptoCallbacks(): MatrixCryptoCallbacks {
    return {
      getSecretStorageKey: async ({ keys }) => {
        const requestedKeyIds = Object.keys(keys ?? {});
        if (requestedKeyIds.length === 0) return null;

        const staged = this.resolveStagedSecretStorageKey(requestedKeyIds);
        if (staged) return staged;

        for (const keyId of requestedKeyIds) {
          const cached = this.secretStorageKeyCache.get(keyId);
          if (cached) return [keyId, new Uint8Array(cached.key)];
        }

        const stored = await loadStoredRecoveryKey();
        if (!stored?.privateKeyBase64) return null;
        const privateKey = new Uint8Array(Buffer.from(stored.privateKeyBase64, "base64"));
        if (privateKey.length === 0) return null;

        if (stored.keyId && requestedKeyIds.includes(stored.keyId)) {
          this.rememberSecretStorageKey(stored.keyId, privateKey, stored.keyInfo);
          return [stored.keyId, privateKey];
        }

        const firstRequestedKeyId = requestedKeyIds[0];
        if (!firstRequestedKeyId) return null;
        this.rememberSecretStorageKey(firstRequestedKeyId, privateKey, stored.keyInfo);
        return [firstRequestedKeyId, privateKey];
      },
      cacheSecretStorageKey: (keyId, keyInfo, key) => {
        const privateKey = new Uint8Array(key);
        const normalizedKeyInfo: MatrixStoredRecoveryKey["keyInfo"] = {
          passphrase: keyInfo?.passphrase,
          name: typeof keyInfo?.name === "string" ? keyInfo.name : undefined,
        };
        this.rememberSecretStorageKey(keyId, privateKey, normalizedKeyInfo);
        loadStoredRecoveryKey().then((stored) => {
          saveRecoveryKeyToDisk({
            keyId,
            keyInfo: normalizedKeyInfo,
            privateKey,
            encodedPrivateKey: stored?.encodedPrivateKey ?? "",
          });
        });
      },
    };
  }

  async getRecoveryKeySummary(): Promise<{
    encodedPrivateKey?: string;
    keyId?: string | null;
    createdAt?: string;
  } | null> {
    const stored = await loadStoredRecoveryKey();
    if (!stored) return null;
    return {
      encodedPrivateKey: stored.encodedPrivateKey,
      keyId: stored.keyId,
      createdAt: stored.createdAt,
    };
  }

  async getSecretStorageKeyCandidate(keyId: string): Promise<Uint8Array | null> {
    const normalizedKeyId = keyId.trim();
    if (!normalizedKeyId) return null;
    const staged = this.resolveStagedSecretStorageKey([normalizedKeyId]);
    if (staged) return staged[1];
    const stored = await loadStoredRecoveryKey();
    if (!stored?.privateKeyBase64) return null;
    const privateKey = new Uint8Array(Buffer.from(stored.privateKeyBase64, "base64"));
    if (privateKey.length === 0) return null;
    this.rememberSecretStorageKey(normalizedKeyId, privateKey, stored.keyInfo);
    return privateKey;
  }

  private resolveEncodedRecoveryKeyInput(params: {
    encodedPrivateKey: string;
    keyId?: string | null;
    keyInfo?: MatrixStoredRecoveryKey["keyInfo"];
  }) {
    const encodedPrivateKey = params.encodedPrivateKey.trim();
    if (!encodedPrivateKey) throw new Error("Matrix recovery key is required");
    let privateKey: Uint8Array;
    try {
      privateKey = decodeRecoveryKey(encodedPrivateKey);
    } catch (err) {
      throw new Error(`Invalid Matrix recovery key: ${formatMatrixErrorMessage(err)}`, { cause: err });
    }
    const keyId = typeof params.keyId === "string" && params.keyId.trim() ? params.keyId.trim() : null;
    return { encodedPrivateKey, privateKey, keyId, keyInfo: params.keyInfo };
  }

  async storeEncodedRecoveryKey(params: {
    encodedPrivateKey: string;
    keyId?: string | null;
    keyInfo?: MatrixStoredRecoveryKey["keyInfo"];
  }): Promise<{ encodedPrivateKey?: string; keyId?: string | null; createdAt?: string }> {
    const prepared = this.resolveEncodedRecoveryKeyInput(params);
    await saveRecoveryKeyToDisk({
      keyId: prepared.keyId,
      keyInfo: prepared.keyInfo,
      privateKey: prepared.privateKey,
      encodedPrivateKey: prepared.encodedPrivateKey,
    });
    if (prepared.keyId) {
      this.rememberSecretStorageKey(prepared.keyId, prepared.privateKey, prepared.keyInfo);
    }
    const summary = await this.getRecoveryKeySummary();
    return summary ?? {};
  }

  stageEncodedRecoveryKey(params: {
    encodedPrivateKey: string;
    keyId?: string | null;
    keyInfo?: MatrixStoredRecoveryKey["keyInfo"];
  }): void {
    const prepared = this.resolveEncodedRecoveryKeyInput(params);
    this.discardStagedRecoveryKey();
    this.stagedRecoveryKey = {
      version: 1,
      createdAt: new Date().toISOString(),
      keyId: prepared.keyId,
      encodedPrivateKey: prepared.encodedPrivateKey,
      privateKeyBase64: Buffer.from(prepared.privateKey).toString("base64"),
      keyInfo: prepared.keyInfo,
    };
  }

  hasStagedRecoveryKeyBeenUsed(): boolean {
    return this.stagedRecoveryKeyUsed;
  }

  async commitStagedRecoveryKey(params?: {
    keyId?: string | null;
    keyInfo?: MatrixStoredRecoveryKey["keyInfo"];
  }): Promise<{ encodedPrivateKey?: string; keyId?: string | null; createdAt?: string } | null> {
    if (!this.stagedRecoveryKey) return this.getRecoveryKeySummary();
    const staged = this.stagedRecoveryKey;
    const privateKey = new Uint8Array(Buffer.from(staged.privateKeyBase64, "base64"));
    const keyId =
      typeof params?.keyId === "string" && params.keyId.trim() ? params.keyId.trim() : staged.keyId;
    await saveRecoveryKeyToDisk({
      keyId,
      keyInfo: params?.keyInfo ?? staged.keyInfo,
      privateKey,
      encodedPrivateKey: staged.encodedPrivateKey,
    });
    this.clearStagedRecoveryKeyTracking();
    return this.getRecoveryKeySummary();
  }

  discardStagedRecoveryKey(): void {
    for (const keyId of this.stagedCacheKeyIds) {
      this.secretStorageKeyCache.delete(keyId);
    }
    this.clearStagedRecoveryKeyTracking();
  }

  async bootstrapSecretStorageWithRecoveryKey(
    crypto: MatrixCryptoBootstrapApi,
    options: {
      setupNewKeyBackup?: boolean;
      allowSecretStorageRecreateWithoutRecoveryKey?: boolean;
      forceNewSecretStorage?: boolean;
      forceNewRecoveryKey?: boolean;
    } = {},
  ): Promise<void> {
    let status: MatrixSecretStorageStatus | null = null;
    const getSecretStorageStatus = crypto.getSecretStorageStatus;
    if (typeof getSecretStorageStatus === "function") {
      try {
        status = await getSecretStorageStatus.call(crypto);
      } catch (err) {
        LogService.warn("MatrixClientLite", "Failed to read secret storage status:", err);
      }
    }

    const hasDefaultSecretStorageKey = Boolean(status?.defaultKeyId);
    const hasKnownInvalidSecrets = Object.values(status?.secretStorageKeyValidityMap ?? {}).some(
      (valid) => !valid,
    );
    let generatedRecoveryKey = false;
    const storedRecovery = await loadStoredRecoveryKey();
    const stagedRecovery = this.stagedRecoveryKey;
    const sourceRecovery =
      options.forceNewRecoveryKey === true ? null : (stagedRecovery ?? storedRecovery);
    let recoveryKey: MatrixGeneratedSecretStorageKey | null = sourceRecovery
      ? {
          keyInfo: sourceRecovery.keyInfo,
          privateKey: new Uint8Array(Buffer.from(sourceRecovery.privateKeyBase64, "base64")),
          encodedPrivateKey: sourceRecovery.encodedPrivateKey,
        }
      : null;

    if (recoveryKey && status?.defaultKeyId) {
      const defaultKeyId = status.defaultKeyId;
      if (!stagedRecovery) {
        this.rememberSecretStorageKey(defaultKeyId, recoveryKey.privateKey, recoveryKey.keyInfo);
        if (storedRecovery && storedRecovery.keyId !== defaultKeyId) {
          await saveRecoveryKeyToDisk({
            keyId: defaultKeyId,
            keyInfo: recoveryKey.keyInfo,
            privateKey: recoveryKey.privateKey,
            encodedPrivateKey: recoveryKey.encodedPrivateKey,
          });
        }
      }
    }

    const ensureRecoveryKey = async (): Promise<MatrixGeneratedSecretStorageKey> => {
      if (recoveryKey) {
        if (stagedRecovery) {
          this.stagedRecoveryKeyUsed = true;
        }
        return recoveryKey;
      }
      if (typeof crypto.createRecoveryKeyFromPassphrase !== "function") {
        throw new Error(
          "Matrix crypto backend does not support recovery key generation (createRecoveryKeyFromPassphrase missing)",
        );
      }
      recoveryKey = await crypto.createRecoveryKeyFromPassphrase();
      await saveRecoveryKeyToDisk(recoveryKey);
      generatedRecoveryKey = true;
      return recoveryKey;
    };

    const shouldRecreateSecretStorage =
      options.forceNewSecretStorage === true ||
      !hasDefaultSecretStorageKey ||
      (!recoveryKey && status?.ready === false) ||
      hasKnownInvalidSecrets;

    if (hasKnownInvalidSecrets) {
      recoveryKey = null;
    }

    const secretStorageOptions: {
      createSecretStorageKey?: () => Promise<MatrixGeneratedSecretStorageKey>;
      setupNewSecretStorage?: boolean;
      setupNewKeyBackup?: boolean;
    } = {
      setupNewKeyBackup: options.setupNewKeyBackup === true,
    };

    if (shouldRecreateSecretStorage) {
      secretStorageOptions.setupNewSecretStorage = true;
      secretStorageOptions.createSecretStorageKey = ensureRecoveryKey;
    }

    try {
      await crypto.bootstrapSecretStorage(secretStorageOptions);
    } catch (err) {
      const shouldRecreateWithoutRecoveryKey =
        options.allowSecretStorageRecreateWithoutRecoveryKey === true &&
        hasDefaultSecretStorageKey &&
        isRepairableSecretStorageAccessError(err);
      if (!shouldRecreateWithoutRecoveryKey) {
        throw err;
      }

      recoveryKey = null;
      LogService.warn(
        "MatrixClientLite",
        "Secret storage exists on the server but local recovery material cannot unlock it; recreating secret storage during explicit bootstrap.",
      );
      await crypto.bootstrapSecretStorage({
        setupNewSecretStorage: true,
        setupNewKeyBackup: options.setupNewKeyBackup === true,
        createSecretStorageKey: ensureRecoveryKey,
      });
    }

    if (generatedRecoveryKey) {
      LogService.warn(
        "MatrixClientLite",
        "Generated Matrix recovery key and saved it to Oracle. Keep the displayed recovery key secure.",
      );
    }
  }

  private clearStagedRecoveryKeyTracking(): void {
    this.stagedRecoveryKey = null;
    this.stagedRecoveryKeyUsed = false;
    this.stagedCacheKeyIds.clear();
  }

  private resolveStagedSecretStorageKey(requestedKeyIds: string[]): [string, Uint8Array] | null {
    const staged = this.stagedRecoveryKey;
    if (!staged?.privateKeyBase64) return null;
    const privateKey = new Uint8Array(Buffer.from(staged.privateKeyBase64, "base64"));
    if (privateKey.length === 0) return null;
    const keyId = staged.keyId && requestedKeyIds.includes(staged.keyId) ? staged.keyId : requestedKeyIds[0];
    if (!keyId) return null;
    this.rememberStagedSecretStorageKey(keyId, privateKey, staged.keyInfo);
    this.stagedCacheKeyIds.add(keyId);
    return [keyId, privateKey];
  }

  private rememberStagedSecretStorageKey(
    keyId: string,
    key: Uint8Array,
    keyInfo?: MatrixStoredRecoveryKey["keyInfo"],
  ): void {
    this.stagedRecoveryKeyUsed = true;
    this.rememberSecretStorageKey(keyId, key, keyInfo);
  }

  private rememberSecretStorageKey(
    keyId: string,
    key: Uint8Array,
    keyInfo?: MatrixStoredRecoveryKey["keyInfo"],
  ): void {
    if (!keyId.trim()) return;
    this.secretStorageKeyCache.set(keyId, {
      key: new Uint8Array(key),
      keyInfo,
    });
  }
}