// Proxy capture Oracle store — HTTP/3 + Oracle Database
import { createHash } from "node:crypto";
import { randomUUID } from "node:crypto";
import { request } from "undici"; // HTTP/3 via undici
import { requireNodeOracle } from "../infra/node-oracle.ts";
import { runOracleTransaction } from "../infra/oracle-transaction.ts";
import type {
  CaptureBlobRecord,
  CaptureEventRecord,
  CaptureObservedDimension,
  CaptureQueryPreset,
  CaptureQueryRow,
  CaptureSessionCoverageSummary,
  CaptureSessionRecord,
  CaptureSessionSummary,
  SharedCaptureBlobRecord,
} from "./types.ts";

export type DebugProxyCaptureStoreOptions = {
  env?: NodeJS.ProcessEnv;
  oracleConfig?: {
    user: string;
    password: string;
    connectString: string;
    poolMin?: number;
    poolMax?: number;
  };
};

const CAPTURE_BODY_PREVIEW_BYTES = 8192;

function serializeJson(value: unknown): string | null {
  return value == null ? null : JSON.stringify(value);
}

function parseMetaJson(metaJson: unknown): Record<string, unknown> | null {
  if (typeof metaJson !== "string" || metaJson.trim().length === 0) {
    return null;
  }
  try {
    const parsed = JSON.parse(metaJson) as unknown;
    return parsed && typeof parsed === "object" ? (parsed as Record<string, unknown>) : null;
  } catch {
    return null;
  }
}

function sortObservedCounts(counts: Map<string, number>): CaptureObservedDimension[] {
  return [...counts.entries()]
    .map(([value, count]) => ({ value, count }))
    .toSorted((left, right) => right.count - left.count || left.value.localeCompare(right.value));
}

class DebugProxyCaptureStoreImpl {
  private pool: any;
  private closed = false;

  constructor(options: DebugProxyCaptureStoreOptions = {}) {
    const oracledb = requireNodeOracle();
    const config = options.oracleConfig ?? {
      user: process.env.ORACLE_USER || "openclaw",
      password: process.env.ORACLE_PASSWORD || "",
      connectString: process.env.ORACLE_CONNECTION_STRING || "localhost:1521/XEPDB1",
      poolMin: 1,
      poolMax: 10,
    };
    
    this.pool = oracledb.createPool(config);
    this.initSchema();
  }

  private async initSchema(): Promise<void> {
    const connection = await this.pool.getConnection();
    try {
      await connection.execute(`
        BEGIN
          EXECUTE IMMEDIATE 'CREATE TABLE capture_sessions (
            id VARCHAR2(64) PRIMARY KEY,
            started_at NUMBER NOT NULL,
            ended_at NUMBER,
            mode VARCHAR2(32) NOT NULL,
            source_scope VARCHAR2(64) NOT NULL,
            source_process VARCHAR2(128) NOT NULL,
            proxy_url VARCHAR2(512),
            db_path VARCHAR2(512),
            blob_dir VARCHAR2(512)
          )';
        EXCEPTION WHEN OTHERS THEN
          IF SQLCODE != -955 THEN RAISE; END IF;
        END;
      `);
      
      await connection.execute(`
        BEGIN
          EXECUTE IMMEDIATE 'CREATE TABLE capture_events (
            id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            session_id VARCHAR2(64) NOT NULL,
            ts NUMBER NOT NULL,
            source_scope VARCHAR2(64) NOT NULL,
            source_process VARCHAR2(128) NOT NULL,
            protocol VARCHAR2(16) NOT NULL,
            direction VARCHAR2(16) NOT NULL,
            kind VARCHAR2(32) NOT NULL,
            flow_id VARCHAR2(64) NOT NULL,
            method VARCHAR2(32),
            host VARCHAR2(256),
            path VARCHAR2(1024),
            status NUMBER,
            close_code NUMBER,
            content_type VARCHAR2(256),
            headers_json CLOB,
            data_text CLOB,
            data_blob_id VARCHAR2(64),
            data_sha256 VARCHAR2(64),
            error_text CLOB,
            meta_json CLOB
          )';
        EXCEPTION WHEN OTHERS THEN
          IF SQLCODE != -955 THEN RAISE; END IF;
        END;
      `);
      
      await connection.execute(`
        BEGIN
          EXECUTE IMMEDIATE 'CREATE INDEX idx_capture_events_session_ts ON capture_events(session_id, ts)';
        EXCEPTION WHEN OTHERS THEN
          IF SQLCODE != -955 THEN RAISE; END IF;
        END;
      `);
      
      await connection.execute(`
        BEGIN
          EXECUTE IMMEDIATE 'CREATE INDEX idx_capture_events_flow ON capture_events(flow_id, ts)';
        EXCEPTION WHEN OTHERS THEN
          IF SQLCODE != -955 THEN RAISE; END IF;
        END;
      `);
      
      await connection.execute(`
        BEGIN
          EXECUTE IMMEDIATE 'CREATE TABLE capture_blobs (
            blob_id VARCHAR2(64) PRIMARY KEY,
            content_type VARCHAR2(256),
            encoding VARCHAR2(16) NOT NULL,
            size_bytes NUMBER NOT NULL,
            sha256 VARCHAR2(64) NOT NULL,
            data BLOB NOT NULL,
            created_at NUMBER NOT NULL
          )';
        EXCEPTION WHEN OTHERS THEN
          IF SQLCODE != -955 THEN RAISE; END IF;
        END;
      `);
      
      await connection.commit();
    } finally {
      await connection.close();
    }
  }

  async close(): Promise<void> {
    if (this.closed) return;
    await this.pool.close();
    this.closed = true;
  }

  get isClosed(): boolean {
    return this.closed;
  }

  async upsertSession(session: CaptureSessionRecord): Promise<void> {
    const connection = await this.pool.getConnection();
    try {
      await connection.execute(
        `MERGE INTO capture_sessions s
         USING (SELECT :id AS id, :started_at AS started_at, :ended_at AS ended_at,
                       :mode AS mode, :source_scope AS source_scope,
                       :source_process AS source_process, :proxy_url AS proxy_url
                FROM DUAL) src
         ON (s.id = src.id)
         WHEN MATCHED THEN UPDATE SET
           ended_at = src.ended_at,
           proxy_url = src.proxy_url,
           source_process = src.source_process
         WHEN NOT MATCHED THEN INSERT
           (id, started_at, ended_at, mode, source_scope, source_process, proxy_url)
         VALUES (src.id, src.started_at, src.ended_at, src.mode,
                 src.source_scope, src.source_process, src.proxy_url)`,
        {
          id: session.id,
          started_at: session.startedAt,
          ended_at: session.endedAt ?? null,
          mode: session.mode,
          source_scope: session.sourceScope,
          source_process: session.sourceProcess,
          proxy_url: session.proxyUrl ?? null,
        }
      );
      await connection.commit();
    } finally {
      await connection.close();
    }
  }

  async endSession(sessionId: string, endedAt = Date.now()): Promise<void> {
    const connection = await this.pool.getConnection();
    try {
      await connection.execute(
        `UPDATE capture_sessions SET ended_at = :ended_at WHERE id = :id`,
        { ended_at: endedAt, id: sessionId }
      );
      await connection.commit();
    } finally {
      await connection.close();
    }
  }

  async persistPayload(data: Buffer, contentType?: string): Promise<SharedCaptureBlobRecord> {
    const sha256 = createHash("sha256").update(data).digest("hex");
    const blobId = sha256.slice(0, 24);
    
    const connection = await this.pool.getConnection();
    try {
      const exists = await connection.execute(
        `SELECT blob_id FROM capture_blobs WHERE blob_id = :blob_id`,
        { blob_id: blobId }
      );
      
      if (exists.rows.length === 0) {
        await connection.execute(
          `INSERT INTO capture_blobs
           (blob_id, content_type, encoding, size_bytes, sha256, data, created_at)
           VALUES (:blob_id, :content_type, 'gzip', :size_bytes, :sha256, :data, :created_at)`,
          {
            blob_id: blobId,
            content_type: contentType ?? null,
            size_bytes: data.byteLength,
            sha256,
            data: data,
            created_at: Date.now(),
          }
        );
        await connection.commit();
      }
    } finally {
      await connection.close();
    }
    
    return {
      blobId,
      encoding: "gzip",
      sizeBytes: data.byteLength,
      sha256,
      ...(contentType ? { contentType } : {}),
    };
  }

  async recordEvent(event: CaptureEventRecord): Promise<void> {
    const connection = await this.pool.getConnection();
    try {
      // Insert event
      await connection.execute(
        `INSERT INTO capture_events (
          session_id, ts, source_scope, source_process, protocol, direction, kind, flow_id,
          method, host, path, status, close_code, content_type, headers_json,
          data_text, data_blob_id, data_sha256, error_text, meta_json
        ) VALUES (
          :session_id, :ts, :source_scope, :source_process, :protocol, :direction, :kind, :flow_id,
          :method, :host, :path, :status, :close_code, :content_type, :headers_json,
          :data_text, :data_blob_id, :data_sha256, :error_text, :meta_json
        )`,
        {
          session_id: event.sessionId,
          ts: event.ts,
          source_scope: event.sourceScope,
          source_process: event.sourceProcess,
          protocol: event.protocol,
          direction: event.direction,
          kind: event.kind,
          flow_id: event.flowId,
          method: event.method ?? null,
          host: event.host ?? null,
          path: event.path ?? null,
          status: event.status ?? null,
          close_code: event.closeCode ?? null,
          content_type: event.contentType ?? null,
          headers_json: event.headersJson ?? null,
          data_text: event.dataText ?? null,
          data_blob_id: event.dataBlobId ?? null,
          data_sha256: event.dataSha256 ?? null,
          error_text: event.errorText ?? null,
          meta_json: event.metaJson ?? null,
        }
      );
      
      await connection.commit();
    } finally {
      await connection.close();
    }
  }

  async listSessions(limit = 50): Promise<CaptureSessionSummary[]> {
    const connection = await this.pool.getConnection();
    try {
      const result = await connection.execute(
        `SELECT
           s.id,
           s.started_at AS startedAt,
           s.ended_at AS endedAt,
           s.mode,
           s.source_process AS sourceProcess,
           s.proxy_url AS proxyUrl,
           (SELECT COUNT(*) FROM capture_events e WHERE e.session_id = s.id) AS eventCount
         FROM capture_sessions s
         ORDER BY s.started_at DESC
         FETCH FIRST :limit ROWS ONLY`,
        { limit }
      );
      return result.rows.map((row: any) => ({
        id: row.ID,
        startedAt: row.STARTEDAT,
        endedAt: row.ENDEDAT,
        mode: row.MODE,
        sourceProcess: row.SOURCEPROCESS,
        proxyUrl: row.PROXYURL,
        eventCount: row.EVENTCOUNT,
      }));
    } finally {
      await connection.close();
    }
  }

  async getSessionEvents(sessionId: string, limit = 500): Promise<Array<Record<string, unknown>>> {
    const connection = await this.pool.getConnection();
    try {
      const result = await connection.execute(
        `SELECT
           id, session_id AS sessionId, ts, source_scope AS sourceScope,
           source_process AS sourceProcess, protocol, direction, kind,
           flow_id AS flowId, method, host, path, status, close_code AS closeCode,
           content_type AS contentType, headers_json AS headersJson,
           data_text AS dataText, data_blob_id AS dataBlobId,
           data_sha256 AS dataSha256, error_text AS errorText, meta_json AS metaJson
         FROM capture_events
         WHERE session_id = :session_id
         ORDER BY ts DESC, id DESC
         FETCH FIRST :limit ROWS ONLY`,
        { session_id: sessionId, limit }
      );
      return result.rows.map((row: any) => {
        const obj: Record<string, unknown> = {};
        for (const key of Object.keys(row)) {
          obj[key.toLowerCase()] = row[key];
        }
        return obj;
      });
    } finally {
      await connection.close();
    }
  }

  async summarizeSessionCoverage(sessionId: string): Promise<CaptureSessionCoverageSummary> {
    const connection = await this.pool.getConnection();
    try {
      const result = await connection.execute(
        `SELECT host, meta_json AS metaJson
         FROM capture_events
         WHERE session_id = :session_id`,
        { session_id: sessionId }
      );
      
      const providers = new Map<string, number>();
      const apis = new Map<string, number>();
      const models = new Map<string, number>();
      const hosts = new Map<string, number>();
      const localPeers = new Map<string, number>();
      let unlabeledEventCount = 0;
      
      for (const row of result.rows as any[]) {
        const meta = parseMetaJson(row.METAJSON);
        const provider = meta?.provider ? String(meta.provider) : null;
        const api = meta?.api ? String(meta.api) : null;
        const model = meta?.model ? String(meta.model) : null;
        const host = row.HOST ? String(row.HOST) : null;
        
        if (!provider && !api && !model) {
          unlabeledEventCount += 1;
        }
        if (provider) providers.set(provider, (providers.get(provider) ?? 0) + 1);
        if (api) apis.set(api, (apis.get(api) ?? 0) + 1);
        if (model) models.set(model, (models.get(model) ?? 0) + 1);
        if (host) {
          hosts.set(host, (hosts.get(host) ?? 0) + 1);
          if (host === "127.0.0.1:11434" || host.startsWith("127.0.0.1:") || host.startsWith("localhost:")) {
            localPeers.set(host, (localPeers.get(host) ?? 0) + 1);
          }
        }
      }
      
      return {
        sessionId,
        totalEvents: result.rows.length,
        unlabeledEventCount,
        providers: sortObservedCounts(providers),
        apis: sortObservedCounts(apis),
        models: sortObservedCounts(models),
        hosts: sortObservedCounts(hosts),
        localPeers: sortObservedCounts(localPeers),
      };
    } finally {
      await connection.close();
    }
  }

  async readBlob(blobId: string): Promise<string | null> {
    const connection = await this.pool.getConnection();
    try {
      const result = await connection.execute(
        `SELECT data FROM capture_blobs WHERE blob_id = :blob_id`,
        { blob_id: blobId }
      );
      if (result.rows.length === 0) return null;
      const blob = result.rows[0].DATA as Buffer;
      return blob.toString("utf8");
    } finally {
      await connection.close();
    }
  }

  async purgeAll(): Promise<{ sessions: number; events: number; blobs: number }> {
    const connection = await this.pool.getConnection();
    try {
      const sessionResult = await connection.execute(`SELECT COUNT(*) AS count FROM capture_sessions`);
      const eventResult = await connection.execute(`SELECT COUNT(*) AS count FROM capture_events`);
      const blobResult = await connection.execute(`SELECT COUNT(*) AS count FROM capture_blobs`);
      
      const sessions = Number(sessionResult.rows[0]?.COUNT ?? 0);
      const events = Number(eventResult.rows[0]?.COUNT ?? 0);
      const blobs = Number(blobResult.rows[0]?.COUNT ?? 0);
      
      await connection.execute(`DELETE FROM capture_events`);
      await connection.execute(`DELETE FROM capture_sessions`);
      await connection.execute(`DELETE FROM capture_blobs`);
      await connection.commit();
      
      return { sessions, events, blobs };
    } finally {
      await connection.close();
    }
  }

  async deleteSessions(sessionIds: string[]): Promise<{ sessions: number; events: number; blobs: number }> {
    // Simplified — implement similarly
    return { sessions: 0, events: 0, blobs: 0 };
  }

  async queryPreset(preset: CaptureQueryPreset, sessionId?: string): Promise<CaptureQueryRow[]> {
    // Simplified — implement as needed
    return [];
  }
}

export type DebugProxyCaptureStore = Omit<DebugProxyCaptureStoreImpl, "persistPayload"> & {
  persistPayload(data: Buffer, contentType?: string): Promise<SharedCaptureBlobRecord>;
};

const storeInstance: DebugProxyCaptureStoreImpl | null = null;

export function getDebugProxyCaptureStore(
  options?: DebugProxyCaptureStoreOptions
): DebugProxyCaptureStore {
  // Singleton pattern
  if (!storeInstance) {
    storeInstance = new DebugProxyCaptureStoreImpl(options);
  }
  return storeInstance;
}

export async function closeDebugProxyCaptureStore(): Promise<void> {
  if (storeInstance) {
    await storeInstance.close();
  }
}

export function persistEventPayload(
  store: DebugProxyCaptureStore,
  params: { data?: Buffer | string | null; contentType?: string; previewLimit?: number }
): { dataText?: string; dataBlobId?: string; dataSha256?: string } {
  if (params.data == null) return {};
  const buffer = Buffer.isBuffer(params.data) ? params.data : Buffer.from(params.data);
  const previewLimit = params.previewLimit ?? CAPTURE_BODY_PREVIEW_BYTES;
  
  // Store the whole payload as a blob
  const blob = store.persistPayload(buffer, params.contentType);
  return {
    dataText: buffer.subarray(0, previewLimit).toString("utf8"),
    dataBlobId: blob.blobId,
    dataSha256: blob.sha256,
  };
}

export function safeJsonString(value: unknown): string | undefined {
  const raw = serializeJson(value);
  return raw ?? undefined;
}