/**
 * Memory Host - Oracle Connection
 * 
 * Всё в Oracle, никакого SQLite!
 */

import oracledb from "oracledb";

let pool: oracledb.Pool | null = null;

export async function initOraclePool(config: {
  user: string;
  password: string;
  connectString: string;
  poolMin?: number;
  poolMax?: number;
}) {
  if (pool) {
    return pool;
  }

  pool = await oracledb.createPool({
    user: config.user,
    password: config.password,
    connectString: config.connectString,
    poolMin: config.poolMin || 2,
    poolMax: config.poolMax || 10,
    poolIncrement: 1,
    poolTimeout: 60,
  });

  await ensureSchema();
  return pool;
}

export function getOraclePool(): oracledb.Pool {
  if (!pool) {
    throw new Error("Oracle pool not initialized. Call initOraclePool() first.");
  }
  return pool;
}

export async function closeOraclePool(): Promise<void> {
  if (pool) {
    await pool.close(0);
    pool = null;
  }
}

async function ensureSchema(): Promise<void> {
  const conn = await pool!.getConnection();
  try {
    await conn.execute(`
      BEGIN
        EXECUTE IMMEDIATE '
          CREATE TABLE sessions (
            id VARCHAR2(64) PRIMARY KEY,
            agent_id VARCHAR2(255) NOT NULL,
            session_key VARCHAR2(500) NOT NULL,
            created_at TIMESTAMP DEFAULT SYSTIMESTAMP,
            updated_at TIMESTAMP DEFAULT SYSTIMESTAMP
          )
        ';
      EXCEPTION
        WHEN OTHERS THEN
          IF SQLCODE != -955 THEN RAISE; END IF;
      END;
    `);
    await conn.execute(`
      BEGIN
        EXECUTE IMMEDIATE '
          CREATE TABLE session_messages (
            id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            session_id VARCHAR2(64) NOT NULL,
            role VARCHAR2(20) NOT NULL,
            content CLOB NOT NULL,
            timestamp TIMESTAMP DEFAULT SYSTIMESTAMP
          )
        ';
      EXCEPTION
        WHEN OTHERS THEN
          IF SQLCODE != -955 THEN RAISE; END IF;
      END;
    `);

    await conn.execute(`
      BEGIN
        EXECUTE IMMEDIATE '
          CREATE INDEX idx_messages_session ON session_messages(session_id)
        ';
      EXCEPTION
        WHEN OTHERS THEN
          IF SQLCODE != -955 THEN RAISE; END IF;
      END;
    `);

    await conn.commit();
  } finally {
    await conn.close();
  }
}

export async function saveSession(params: {
  agentId: string;
  sessionKey: string;
}): Promise<void> {
  const conn = await pool!.getConnection();
  try {
    const id = `${params.agentId}:${params.sessionKey}`;
    await conn.execute(
      `MERGE INTO sessions target
       USING (SELECT :id AS id FROM DUAL) source
       ON (target.id = source.id)
       WHEN MATCHED THEN UPDATE SET updated_at = SYSTIMESTAMP
       WHEN NOT MATCHED THEN INSERT (id, agent_id, session_key)
         VALUES (:id, :agentId, :sessionKey)`,
      {
        id,
        agentId: params.agentId,
        sessionKey: params.sessionKey,
      }
    );
    await conn.commit();
  } finally {
    await conn.close();
  }
}

export async function saveMessage(params: {
  sessionId: string;
  role: "user" | "assistant";
  content: string;
}): Promise<void> {
  const conn = await pool!.getConnection();
  try {
    await conn.execute(
      `INSERT INTO session_messages (session_id, role, content)
       VALUES (:sessionId, :role, :content)`,
      {
        sessionId: params.sessionId,
        role: params.role,
        content: params.content,
      }
    );
    await conn.commit();
  } finally {
    await conn.close();
  }
}

export async function getMessages(params: {
  sessionId: string;
  limit?: number;
}): Promise<any[]> {
  const conn = await pool!.getConnection();
  try {
    const result = await conn.execute(
      `SELECT role, content, timestamp
       FROM session_messages
       WHERE session_id = :sessionId
       ORDER BY timestamp ASC
       FETCH FIRST :limit ROWS ONLY`,
      {
        sessionId: params.sessionId,
        limit: params.limit || 1000,
      }
    );
    return result.rows || [];
  } finally {
    await conn.close();
  }
}

export async function deleteSession(params: {
  sessionId: string;
}): Promise<void> {
  const conn = await pool!.getConnection();
  try {
    await conn.execute(
      `DELETE FROM session_messages WHERE session_id = :sessionId`,
      { sessionId: params.sessionId }
    );
    await conn.execute(
      `DELETE FROM sessions WHERE id = :sessionId`,
      { sessionId: params.sessionId }
    );
    await conn.commit();
  } finally {
    await conn.close();
  }
}