/**
 * Memory Host - Oracle Session Files
 */

import oracledb from "oracledb";

const TABLE_SESSIONS = "sessions";
const TABLE_MESSAGES = "session_messages";

async function ensureTables(pool: oracledb.Pool): Promise<void> {
  const conn = await pool.getConnection();
  try {
    await conn.execute(`
      BEGIN
        EXECUTE IMMEDIATE '
          CREATE TABLE ${TABLE_SESSIONS} (
            id VARCHAR2(64) PRIMARY KEY,
            agent_id VARCHAR2(255) NOT NULL,
            session_key VARCHAR2(500) NOT NULL,
            created_at TIMESTAMP DEFAULT SYSTIMESTAMP,
            updated_at TIMESTAMP DEFAULT SYSTIMESTAMP
          )
        ';
      EXCEPTION
        WHEN OTHERS THEN
          IF SQLCODE != -955 THEN RAISE; END IF;
      END;
    `);

    await conn.execute(`
      BEGIN
        EXECUTE IMMEDIATE '
          CREATE TABLE ${TABLE_MESSAGES} (
            id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            session_id VARCHAR2(64) NOT NULL,
            role VARCHAR2(20) NOT NULL,
            content CLOB NOT NULL,
            timestamp TIMESTAMP DEFAULT SYSTIMESTAMP
          )
        ';
      EXCEPTION
        WHEN OTHERS THEN
          IF SQLCODE != -955 THEN RAISE; END IF;
      END;
    `);

    await conn.execute(`
      BEGIN
        EXECUTE IMMEDIATE '
          CREATE INDEX idx_messages_session ON ${TABLE_MESSAGES}(session_id)
        ';
      EXCEPTION
        WHEN OTHERS THEN
          IF SQLCODE != -955 THEN RAISE; END IF;
      END;
    `);
    await conn.commit();
  } finally {
    await conn.close();
  }
}

export async function saveSession(params: {
  pool: oracledb.Pool;
  agentId: string;
  sessionKey: string;
}) {
  await ensureTables(params.pool);
  const conn = await params.pool.getConnection();
  try {
    const id = `${params.agentId}:${params.sessionKey}`;
    await conn.execute(
      `MERGE INTO ${TABLE_SESSIONS} target
       USING (SELECT :id AS id FROM DUAL) source
       ON (target.id = source.id)
       WHEN MATCHED THEN UPDATE SET updated_at = SYSTIMESTAMP
       WHEN NOT MATCHED THEN INSERT (id, agent_id, session_key)
         VALUES (:id, :agentId, :sessionKey)`,
      {
        id,
        agentId: params.agentId,
        sessionKey: params.sessionKey,
      }
    );
    await conn.commit();
  } finally {
    await conn.close();
  }
}

export async function saveMessage(params: {
  pool: oracledb.Pool;
  sessionId: string;
  role: "user" | "assistant";
  content: string;
}) {
  await ensureTables(params.pool);
  const conn = await params.pool.getConnection();
  try {
    await conn.execute(
      `INSERT INTO ${TABLE_MESSAGES} (session_id, role, content)
       VALUES (:sessionId, :role, :content)`,
      {
        sessionId: params.sessionId,
        role: params.role,
        content: params.content,
      }
    );
    await conn.commit();
  } finally {
    await conn.close();
  }
}

export async function getSessionMessages(params: {
  pool: oracledb.Pool;
  sessionId: string;
  limit?: number;
}) {
  await ensureTables(params.pool);
  const conn = await params.pool.getConnection();
  try {
    const result = await conn.execute(
      `SELECT role, content, timestamp 
       FROM ${TABLE_MESSAGES}
       WHERE session_id = :sessionId
       ORDER BY timestamp ASC
       FETCH FIRST :limit ROWS ONLY`,
      {
        sessionId: params.sessionId,
        limit: params.limit || 1000,
      }
    );
    return result.rows || [];
  } finally {
    await conn.close();
  }
}

export async function deleteSession(params: {
  pool: oracledb.Pool;
  sessionId: string;
}) {
  await ensureTables(params.pool);
  const conn = await params.pool.getConnection();
  try {
    await conn.execute(
      `DELETE FROM ${TABLE_MESSAGES} WHERE session_id = :sessionId`,
      { sessionId: params.sessionId }
    );
    await conn.execute(
      `DELETE FROM ${TABLE_SESSIONS} WHERE id = :sessionId`,
      { sessionId: params.sessionId }
    );
    await conn.commit();
  } finally {
    await conn.close();
  }
}